/** @deprecated Import from @/lib/catalogStore instead */
export {
  slugifyName,
  buildBrandId,
  brandOptionKey,
  loadCatalog,
  loadAdminCatalog,
  getCatalogSync,
  refreshCatalog,
  invalidateCatalogCache,
  getCategoryBySlug,
  getBrandsForCategorySlug,
  getBrandBySlug,
  getBrandById,
  addCategory,
  updateCategory,
  deleteCategory,
  addBrand,
  updateBrand,
  deleteBrand,
  addStoredCategory,
  addStoredBrand,
  getStoredCategories,
  getStoredBrands,
  saveStoredCategories,
  saveStoredBrands,
  updateStoredCategory,
  deleteStoredCategory,
  updateStoredBrand,
  deleteStoredBrand,
} from "@/lib/catalogStore";
